 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$kevinoli-portfolio/portfolio:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$kevinoli-portfolio/portfolio:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'SERVICE-NAME'
   - '--image'
   - 'gcr.io/$kevinoli-portfolio/portfolio:$COMMIT_SHA'
   - '--region'
   - 'REGION'
 images:
 - 'gcr.io/$kevinoli-portfolio/portfolio:$COMMIT_SHA'
#  steps:
# # Build the Node.js application
# - name: "node:20-alpine"
#   entrypoint: "sh"
#   args: ["-c", "npm install && npm run build"]
#   dir: "/workspace"
  
# # Build the Nginx image and copy the built files
# - name: "gcr.io/cloud-builders/docker"
#   args: ["build", "-t", "gcr.io/$kevinoli-portfolio/latest", "."]
#   dir: "/workspace"
  
# # Push the Nginx image to Google Container Registry
# - name: "gcr.io/cloud-builders/docker"
#   args: ["push", "gcr.io/$kevinoli-portfolio/latest"]
  
# # Deploy to Google Cloud Run
# - name: "gcr.io/cloud-builders/gcloud"
#   args: ["run", "deploy", "my-app", "--image", "gcr.io/$kevinoli-portfolio/latest", "--platform", "managed", "--region", "us-west4"]
